serve:
  proxy:
    port: 4455 # run the proxy at port 4455
  api:
    port: 4456 # run the api at port 4456

access_rules:
  repositories:
    - file://etc/config/oathkeeper/rules.json

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  hydrator:
    enabled: true
    config:
      api:
        url: http://host.docker.internal:8080/hydrator
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
        # You could add some other headers, for example with data from the
        # session.
        # X-Some-Arbitrary-Data: "{{ print .Extra.some.arbitrary.data }}"
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: http://localhost:4455/
      jwks_url: file:///etc/config/oathkeeper/jwks.json

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

authenticators:
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: "http://hydra:4445/oauth2/introspect"

  noop:
    enabled: true

  anonymous:
    enabled: true
    config:
      subject: guest