version: '3.8'

services:
  oathkeeper:
    image: oryd/oathkeeper:v0.38.14-alpine
    ports:
      - "4455:4455"
      - "4456:4456"
    command:
      serve --config=/etc/config/oathkeeper/config.yaml
    volumes:
      - type: bind
        source: ./oathkeeper
        target: /etc/config/oathkeeper
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.10.2
    environment:
      - SECRETS_SYSTEM=11sCysLCB8B3yIm4GJzssLP1lxI95zKk
      - DSN=postgres://hydra:secret@hydra-postgres:5432/hydra?sslmode=disable
    ports:
      - "9000:4444"
      - "9001:4445"
    depends_on:
      - hydra-postgres
      - hydra-migration
    entrypoint: [ "hydra", "serve", "all", "--dangerous-force-http" ]
    restart: on-failure

  hydra-migration:
    image: oryd/hydra:v1.10.2
    environment:
      - DSN=postgres://hydra:secret@hydra-postgres:5432/hydra?sslmode=disable
    depends_on:
      - hydra-postgres
    entrypoint: [ "hydra", "migrate", "sql", "--yes", "-e" ]

  hydra-postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra

